apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.apollo.staticIP }}
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: {{ .Chart.Name }}-backend-service
          servicePort: 4040