apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-backend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.apollo.staticIP }}
    ingress.kubernetes.io/enable-cors: "true"
spec:
  backend:
    serviceName: {{ .Chart.Name }}-backend-service
    servicePort: 4040