apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend-service
spec:
  selector:
    app: {{ .Chart.Name }}-backend
  type: NodePort
  ports:
  - name: backend
    port: 4040
    targetPort: 4040